name: KMP library compilation check

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  test:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check library build
      run: ./gradlew -PlibraryPublish detekt :errors:publishToMavenLocal
    - name: Check library sample
      run: ./gradlew detekt :sample:mpp-library:build
